// Codes By Mahdi Tasha
// Importing Part
import IconComponent from './iconComponent';

// Defining type of props
interface openedInterface {}

// Exporting functional component as default
export default function DatePickerComponent():JSX.Element{
    // Returning JSX
    return(
        <>
            <button>
                <span>--/--/--</span>
                <IconComponent type={'calender'}/>
            </button>
            <div>
                <div>
                    <button>
                        <span>April 2023</span>
                        <IconComponent type={'chevron-down'}/>
                    </button>
                    <div>
                        <button><IconComponent type={'chevron-left'}/></button>
                        <button><IconComponent type={'chevron-right'}/></button>
                    </div>
                </div>
                <div>
                    <span>1900</span>
                    <span>1901</span>
                    <span>1902</span>
                    <span>1903</span>
                    <span>1904</span>
                    <span>1905</span>
                    <span>1906</span>
                    <span>1907</span>
                    <span>1908</span>
                    <span>1909</span>
                    <span>1910</span>
                    <span>1911</span>
                    <span>1912</span>
                    <span>1913</span>
                    <span>1914</span>
                    <span>1915</span>
                    <span>1916</span>
                    <span>1917</span>
                    <span>1918</span>
                    <span>1919</span>
                    <span>1920</span>
                    <span>1921</span>
                    <span>1922</span>
                    <span>1923</span>
                    <span>1924</span>
                    <span>1925</span>
                    <span>1926</span>
                    <span>1927</span>
                    <span>1928</span>
                    <span>1929</span>
                    <span>1930</span>
                    <span>1931</span>
                    <span>1932</span>
                    <span>1933</span>
                    <span>1934</span>
                    <span>1935</span>
                    <span>1936</span>
                    <span>1937</span>
                    <span>1938</span>
                    <span>1939</span>
                    <span>1940</span>
                    <span>1941</span>
                    <span>1942</span>
                    <span>1943</span>
                    <span>1944</span>
                    <span>1945</span>
                    <span>1946</span>
                    <span>1947</span>
                    <span>1948</span>
                    <span>1949</span>
                    <span>1950</span>
                    <span>1951</span>
                    <span>1952</span>
                    <span>1953</span>
                    <span>1954</span>
                    <span>1955</span>
                    <span>1956</span>
                    <span>1957</span>
                    <span>1958</span>
                    <span>1959</span>
                    <span>1960</span>
                    <span>1961</span>
                    <span>1962</span>
                    <span>1963</span>
                    <span>1964</span>
                    <span>1965</span>
                    <span>1966</span>
                    <span>1967</span>
                    <span>1968</span>
                    <span>1969</span>
                    <span>1970</span>
                    <span>1971</span>
                    <span>1972</span>
                    <span>1973</span>
                    <span>1974</span>
                    <span>1975</span>
                    <span>1976</span>
                    <span>1977</span>
                    <span>1978</span>
                    <span>1979</span>
                    <span>1980</span>
                    <span>1981</span>
                    <span>1982</span>
                    <span>1983</span>
                    <span>1984</span>
                    <span>1985</span>
                    <span>1986</span>
                    <span>1987</span>
                    <span>1988</span>
                    <span>1989</span>
                    <span>1990</span>
                    <span>1991</span>
                    <span>1992</span>
                    <span>1993</span>
                    <span>1994</span>
                    <span>1995</span>
                    <span>1996</span>
                    <span>1997</span>
                    <span>1998</span>
                    <span>1999</span>
                    <span>2000</span>
                    <span>2000</span>
                    <span>2001</span>
                    <span>2002</span>
                    <span>2003</span>
                    <span>2004</span>
                    <span>2005</span>
                    <span>2006</span>
                    <span>2007</span>
                    <span>2008</span>
                    <span>2009</span>
                    <span>2010</span>
                    <span>2011</span>
                    <span>2012</span>
                    <span>2013</span>
                    <span>2014</span>
                    <span>2015</span>
                    <span>2016</span>
                    <span>2017</span>
                    <span>2018</span>
                    <span>2019</span>
                    <span>2020</span>
                    <span>2021</span>
                    <span>2022</span>
                    <span>2023</span>
                    <span>2024</span>
                    <span>2025</span>
                    <span>2026</span>
                    <span>2027</span>
                    <span>2028</span>
                    <span>2029</span>
                    <span>2030</span>
                    <span>2031</span>
                    <span>2032</span>
                    <span>2033</span>
                    <span>2034</span>
                    <span>2035</span>
                    <span>2036</span>
                    <span>2037</span>
                    <span>2038</span>
                    <span>2039</span>
                    <span>2040</span>
                    <span>2041</span>
                    <span>2042</span>
                    <span>2043</span>
                    <span>2044</span>
                    <span>2045</span>
                    <span>2046</span>
                    <span>2047</span>
                    <span>2048</span>
                    <span>2049</span>
                    <span>2050</span>
                    <span>2051</span>
                    <span>2052</span>
                    <span>2053</span>
                    <span>2054</span>
                    <span>2055</span>
                    <span>2056</span>
                    <span>2057</span>
                    <span>2058</span>
                    <span>2059</span>
                    <span>2060</span>
                    <span>2061</span>
                    <span>2062</span>
                    <span>2063</span>
                    <span>2064</span>
                    <span>2065</span>
                    <span>2066</span>
                    <span>2067</span>
                    <span>2068</span>
                    <span>2069</span>
                    <span>2070</span>
                    <span>2071</span>
                    <span>2072</span>
                    <span>2073</span>
                    <span>2074</span>
                    <span>2075</span>
                    <span>2076</span>
                    <span>2077</span>
                    <span>2078</span>
                    <span>2079</span>
                    <span>2080</span>
                    <span>2081</span>
                    <span>2082</span>
                    <span>2083</span>
                    <span>2084</span>
                    <span>2085</span>
                    <span>2086</span>
                    <span>2087</span>
                    <span>2088</span>
                    <span>2089</span>
                    <span>2090</span>
                    <span>2091</span>
                    <span>2092</span>
                    <span>2093</span>
                    <span>2094</span>
                    <span>2095</span>
                    <span>2096</span>
                    <span>2097</span>
                    <span>2098</span>
                    <span>2099</span>
                    <span>3000</span>
                </div>
                <div>
                    <div>
                        <span>S</span>
                        <span>M</span>
                        <span>T</span>
                        <span>W</span>
                        <span>T</span>
                        <span>F</span>
                        <span></span>
                    </div>
                    <div>
                        <div>
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                            <span>1</span>
                            <span>2</span>
                            <span>3</span>
                            <span>4</span>
                            <span>5</span>
                            <span>6</span>
                            <span>7</span>
                            <span>8</span>
                            <span>9</span>
                            <span>10</span>
                            <span>11</span>
                            <span>12</span>
                            <span>13</span>
                            <span>14</span>
                            <span>15</span>
                            <span>16</span>
                            <span>17</span>
                            <span>18</span>
                            <span>19</span>
                            <span>20</span>
                            <span>21</span>
                            <span>22</span>
                            <span>23</span>
                            <span>24</span>
                            <span>25</span>
                            <span>26</span>
                            <span>27</span>
                            <span>28</span>
                            <span>29</span>
                            <span>30</span>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}